- name: Install stow
  apt: name=stow
  tags:
    - install
    - dotfiles

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "https://github.com/pavva91/dotfiles"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles

- name: Rename .zshrc
  shell: mv ~/.zshrc ~/.zshrc.bak
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./stowAutomation.sh
  tags:
    - install
    - dotfiles
