- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
      - nvim
      - install
      - dotfiles
  tasks:
    - include: ./tasks/install.yml
    - include: ./tasks/node.yml
    - include: ./tasks/zsh.yml
    - include: ./tasks/nvim.yml
    - include: ./tasks/dotfiles.yml
