#!/bin/bash

##Check VPN status
# GET_VPN=$(ip route | grep tun0 | wc -l)
GET_VPN=$(ip route | grep -c tun0)

country_iso=$(curl -s ifconfig.co/json | awk -F "\"" '/country_iso/ {print $4}')

if [ "$GET_VPN" != "0" ];
then
    STATUS="ON: $country_iso"
else
    STATUS="OFF: $country_iso"
fi

echo "$STATUS" # full text
echo "$STATUS" # short text

##Colors
if [[ "$STATUS" == *"ON"* ]]
then
    echo "#00ff00"
else
    echo "#ff0000"
fi
