#!/bin/bash

STATUS=$(curl -Ss "https://wttr.in/fano?0&T&Q" | cut -c 16- | head -2 | xargs echo)
# STATUS=$(command=curl -Ss "https://wttr.in/${LOCATION_WEATHER}?0&T&Q" | cut -c 16- | head -2 | xargs echo)

echo $STATUS
