#!/bin/bash

##Check VPN status
# GET_VPN=$(nmcli con show -a | grep tun0 | cut -d ' ' -f1)
# GET_VPN=$(nmcli -t con show -a | grep tun0 | awk -F  ':' '{ print $1 }')
GET_VPN=$(nmcli con show -a | grep tun0 | awk '{ print $1 }')

##Store status in STATUS
if [[ $GET_VPN == *"tun0"* ]]
then
    STATUS=ON
else
    STATUS=OFF
fi

echo $STATUS # full text
echo $STATUS # short text

##Colors
if [[ "$STATUS" == "ON" ]]
then
    echo "#00ff00"
else
    echo "#ff0000"
fi
