vim.keymap.set("n", "<leader>tNF", "<cmd>lua require('neotest').run.run({vim.fn.expand('%'), strategy = 'dap'})<cr>", {desc = "Debug File" })
vim.keymap.set("n", "<leader>tNL", "<cmd>lua require('neotest').run.run_last({strategy = 'dap'})<cr>", {desc = "Debug [L]ast" })
vim.keymap.set("n", "<leader>tNa", "<cmd>lua require('neotest').run.attach()<cr>", {desc = "[A]ttach" })
vim.keymap.set("n", "<leader>tNs", "<cmd>lua require('neotest').run.run(vim.fn.getcwd())<cr>", {desc = "All the Test [S]uite" })
vim.keymap.set("n", "<leader>tNf", "<cmd>lua require('neotest').run.run(vim.fn.expand('%'))<cr>", {desc = "[F]ile" })
vim.keymap.set("n", "<leader>tNn", "<cmd>lua require('neotest').run.run()<cr>", {desc = "[N]earest" })
vim.keymap.set("n", "<leader>tNl", "<cmd>lua require('neotest').run.run_last()<cr>", {desc = "[L]ast" })
vim.keymap.set("n", "<leader>tNN", "<cmd>lua require('neotest').run.run({strategy = 'dap'})<cr>", {desc = "Debug Nearest" })
vim.keymap.set("n", "<leader>tNo", "<cmd>lua require('neotest').output.open({ enter = true })<cr>", {desc = "[O]utput result" })
vim.keymap.set("n", "<leader>tNx", "<cmd>lua require('neotest').run.stop()<cr>", {desc = "Stop [X]" })
vim.keymap.set("n", "<leader>tNS", "<cmd>lua require('neotest').summary.toggle()<cr>", {desc = "[S]ummary" })
vim.keymap.set("n", "[n", "<cmd>lua require('neotest').jump.prev({ status = \"failed\" })<cr>", {desc = "Jump to Previous test failure" })
vim.keymap.set("n", "]n", "<cmd>lua require('neotest').jump.next({ status = \"failed\" })<cr>", {desc = "Jump to [N]ext test failure" })
