- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    # TODO: download font
    # TODO: Setup Tmux plugin (tpm)
    # TODO: Install pyenv
    - ansible.builtin.include_tasks: ./tasks/install.yml
    - ansible.builtin.include_tasks: ./tasks/node.yml
    - ansible.builtin.include_tasks: ./tasks/zsh.yml
    - ansible.builtin.include_tasks: ./tasks/nvim.yml
    - ansible.builtin.include_tasks: ./tasks/dotfiles.yml
    - ansible.builtin.include_tasks: ./tasks/install-languages.yml
